---
steps:
  - label: Generate Sentence
    key: sentence
    env:
      LOREMIPSUM_ACTION: SENTENCE
      SENTENCE_MAX_CHAR: 20
      ANNOTATE: true
    plugins:
      docker#v5.12.0:
        image: python:3.13
        always_pull: true
        volumes:
          - .:/buildkite-py-lorem-demo
    command: "python3 .buildkite/assets/scripts/lorem_ipsum.py"

  - label: Generate Paragraph
    key: paragraph
    depends_on: sentence
    env:
      LOREMIPSUM_ACTION: PARAGRAPH
      PARAGRAPH_MAX_CHAR: 100
      ANNOTATE: true
    plugins:
      docker#v5.12.0:
        image: python:3.13
        always_pull: true
        volumes:
          - .:/buildkite-py-lorem-demo
    command: "python3 .buildkite/assets/scripts/lorem_ipsum.py"